name: (branch main) Automations

on:
  push:
    branches:
      - main

jobs:
  lint-code:
    uses: ./.github/workflows/shared-lint-code.yml

  package-distribution-files:
    uses: ./.github/workflows/shared-package-distribution-files.yml
